Videl\PublishMyCodeBundle\Entity\Code:
    type: entity
    table: null
    repositoryClass: Videl\PublishMyCodeBundle\Entity\CodeRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        code:
            type: text
            column: Code
    lifecycleCallbacks: {  }
