Videl\PublishMyCodeBundle\Entity\Tag:
    type: entity
    table: null
    repositoryClass: Videl\PublishMyCodeBundle\Entity\TagRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 255
    lifecycleCallbacks: {  }
