publish_my_code_homepage:
    pattern:  /
    defaults: { _controller: PublishMyCodeBundle:Default:index }

publish_my_code_post_crud:
    resource: '@PublishMyCodeBundle/Resources/config/routing/post.yml'
    prefix:	/post

publish_my_code_code_crud:
    resource: '@PublishMyCodeBundle/Resources/config/routing/code.yml'
    prefix:	/code
